/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Josh Johanson (https://sketchfab.com/johansome)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medium-cute-robo-drone-0609b2daeab3477497ef52cca3b6801c
Title: Medium - Cute Robo-Drone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const HoverRobot = (props) => {
  const { nodes, materials } = useGLTF('models/dronebot.glb')
  const groupRef = useRef()
  
  // Use useFrame for animation
  useFrame((state) => {
    if (groupRef.current) {
      // Calculate hover motion: up and down over time
      // Using sine wave for smooth up and down motion
      const hoverAmount = Math.sin(state.clock.elapsedTime) * 0.2
      
      // Apply the hover animation to the main group
      groupRef.current.position.y = 6 + hoverAmount
      
      // Optional: Add slight rotation or other subtle movements
      // groupRef.current.rotation.y += 0.005
    }
  })
  
  return (
    <group {...props} dispose={null}>
      <group 
        ref={groupRef}
        position={[-1.5, 8, 4.251]} 
        rotation={[Math.PI / 2, 0, 0.5]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rockets__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fins__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.faceplate__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.head__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.head__0_1.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.emiss__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lhnd__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rhnd__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wre__0.geometry}
            material={materials['Scene_-_Root']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/dronebot.glb');

export default HoverRobot;